baseURL: https://amstatista.netlify.app
title: AM Analytics
theme: hugo-theme-m10c
paginate: 8
menu:

  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: about
      name: About
      url: /about/
      weight: 3
params:
  author: John Doe
  description: I love working with data and crunching numbers. Content will range from stats to just about anything that catches my eye. Avid cinephile.
  menu_item_separator: ' - '
  social:
    - icon: github
      name: Github
      url: https://github.com/gohugoio
    - icon: twitter
      name: Twitter
      url: https://twitter.com/roamdeuter
